name: workspace-nouveau

services:
  workspace:
    image: workspace-nouveau:latest
    build:
      context: .
    environment:
      - MAIN_USER=dtaas-user
    ports:
      - "8080:8080"
    shm_size: 512m
    volumes:
      - ./persistent_dir:/workspace
    develop:
      watch:
        - path: .
          action: rebuild
